### ISSUE TITLE
stop qucikly

### ISSUE THREAD

**Issue by ZSC0810** [ayadim/Nuclei-bug-hunter#1]
thanks for you share, but wen i use your template，nuclei always finished fast, even if supported url is mostly 165926 ~~~

**Comment by ayadim** [comment]
> thanks for you share, but wen i use your template，nuclei always finished fast, even if supported url is mostly 165926 ~~~

hi,
i guess the templates didn't find any match,  gor what purpose you did use them ?

**Comment by ZSC0810** [comment]
just for find bug and then submmit~

**Comment by ZSC0810** [comment]
![image](https://user-images.githubusercontent.com/23701024/231059391-d3d937dc-b983-422b-8b85-8f429d87ec69.png)

i feel so fast finished,and i think should find someting~

**Comment by ayadim** [comment]
> ![image](https://user-images.githubusercontent.com/23701024/231059391-d3d937dc-b983-422b-8b85-8f429d87ec69.png)
> 
> i feel so fast finished,and i think should find someting~

hi again .
i see the problem. the templates are for files not for online scan .. 
if you have list of endpoints/ js files you can get results.
again the templates aren't for online scan just scan files on your machine that's why it's fast.
