### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by erik-451** [ayadim/Nuclei-bug-hunter#2]
It could be nice to add extensions such as .json , .db, .sh scripts, etc. 

[interstingExtensions.yaml](https://github.com/ayadim/Nuclei-bug-hunter/blob/main/file/file-extensions/interstingExtensions.yaml)

**Comment by ayadim** [comment]
hello. 
sorry for being late I open my editor and am working on it now, I am going to fill the file for more if you have any other suggestions.
regards

**Comment by ayadim** [comment]
the template was renamed to :  url-extension-inspector.yaml

[Link] (https://github.com/ayadim/Nuclei-bug-hunter/blob/main/file/url-analyse/url-extension-inspector.yaml)

Regards
